---
# Name of the job that is going to be running which in this case is configuring the app server
- name: Configure app server
  # The term app_servers is coming from inventory1.yml hence this is making it run on foo-app instance
  hosts: app_servers
  remote_user: ubuntu
  # have sudo rights when you login
  become: yes # sudo

  # Similar to github actions workflow there are tasks and each task has its own name
  tasks:
  # Installing nginx as an HTML needs to be uploaded
  - name: Install nginx
    # This step has a built in plugin. 'apt' is a package manager for ubuntu responsible for installing stuff in ubuntu. 
    # Here apt is being used to install nginx
    ansible.builtin.apt:
      name: nginx
      state: present     # When ansible is ran it is going to check if nginx is installed and if it is not then it is going to install it
  # Running a simple copy command
  - name: Upload home page to web site
    # copy - built in command
    # Here, the contents within index.ejs file is being copied to  into index.html file
    copy:
      src: '/root/RMIT/A2/cosc2759-assignment-2-Nushura/app/views/pages/index.ejs'
      dest: /var/www/html/index.html
  
  - name: Upload foo app page to web site
    # needs: Upload home page to web site
    # copy - built in command
    # Here, the contents within foo.ejs file is being copied to  into index.html file
    copy:
      src: '/root/RMIT/A2/cosc2759-assignment-2-Nushura/app/views/pages/foos.ejs'
      dest: '/var/www/html/foos.html'

